### PR TITLE
Required library is added in source/backend/cpu/CPURuntime.hpp

### PR DESCRIPTION
**Pull request by Akshaysharma29**
I Have added Required library in source/backend/cpu/CPURuntime.hpp without which I am not able to cmake this repository.
Thanks

### CODE REVIEW

**Comment by czy2014hust** [comment]
what kind of platform do you use，and your g++ version？

**Comment by Akshaysharma29** [comment]
jetson nano

**Comment by jxt1234** [comment]
Please signed the CLA, thanks.

**Comment by czy2014hust** [comment]
Please delete the `include` in the andriod macro, and put the `#include <stdint.h>` inside macro CPURuntime_hpp

**Comment by Akshaysharma29** [comment]
I have signed the CLA but it is still showing that I have not signed.

**Comment by jxt1234** [comment]
It seems akshaysharma01 should signed CLA also. Or you can create a new branch and commit by yourself.

**Pull request closed without merging**
