### PR TITLE
fix compareTensors() function

### PR DESCRIPTION
**Pull request by korolevivan**

### CODE REVIEW

**Comment by leo-nullptr** [comment]
@korolevivan You should use fabsf for `float` type.

**Comment by korolevivan** [comment]
> @korolevivan You should use `fabsf` for `float` type.

thanks, fixed)

**Comment by li-qing** [comment]
sign the CLA plz so that I can merge your pull request

**Comment by gdh1995** [comment]
Then I think the line 132 should check `!std::isinf(pb[i])` first. Am I right?

**Pull request closed without merging**
