### PR TITLE
backend: cpu: runtime: linux aarch64 hwcaps setting for ARMV82

### PR DESCRIPTION
**Pull request by snadampal**
Adding support for detecting fp16 and dot caps for aarch64 linux platforms.

### CODE REVIEW

**Review by jxt1234 — APPROVED** [review]

**Comment by jxt1234** [comment]
Please sign CLA and then I can merge it.

**Comment by snadampal** [comment]
Hi @jxt1234 , CLA is signed, I also rebased the commits to the latest master.

**Comment by snadampal** [comment]
Hi @jxt1234 , would you be able to check my CLA status? I wanted to use my corporate CLA, not the individual one. I'm not sure which CLA signing is active for this project.

**Comment by omerh** [comment]
Hi @jxt1234 
What is the CLA status? can this be merged?

**Review by jxt1234 — APPROVED** [review]

**Comment by snadampal** [comment]
Hi @jxt1234, could you please check which CLA is in effect. Thank you!

**Pull request merged**
