### PR TITLE
Fix dimension type

### PR DESCRIPTION
**Pull request by daquexian**
The return value of `Tensor::DimensionType Tensor::getDimensionType() const` is wrong and inconsistent with `static Tensor::DimensionType getDimType(const Tensor* origin)`

### CODE REVIEW

**Comment by li-qing** [comment]
getDimType is a private function in tensor.cpp, and it's implemented intentionally in this way to simplify dimension type handle logic.

**Comment by daquexian** [comment]
> getDimType is a private function in tensor.cpp, and it's implemented intentionally in this way to simplify dimension type handle logic.

So is it an intended behavior that `Tensor::DimensionType Tensor::getDimensionType() const` returns CAFFE even if the right type is CAFFE_C4?

**Comment by jxt1234** [comment]
"So is it an intended behavior that Tensor::DimensionType Tensor::getDimensionType() const returns CAFFE even if the right type is CAFFE_C4?"  Yes.

This is a legacy problem. Before the modification, we need to correct the relevant code.

**Comment by li-qing** [comment]
yes, so far.

**Pull request closed without merging**
